version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: quotevault_postgres
    environment:
      POSTGRES_DB: quotevault
      POSTGRES_USER: lentaj
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  pgdata:
